version: "3.9"
services:
    backend:
        image: jorawarsingh/skejool-server:1.0
        container_name: server-container
        build:
            context: ./server
        ports:
            - "9000:80"
    frontend:
        image: jorawarsingh/skejool-client:1.0
        container_name: client-container
        build:
            context: ./client
        ports:
            - "4200:80"
        depends_on:
            - backend