spring:
  application:
    name: skejool
  datasource:
    url: jdbc:postgresql://localhost:5432/skejool
    username: ebnite
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public


server:
  port: 80


